### ISSUE TITLE
Why does AccessToken type contain both expires and expires_in properties?

### ISSUE THREAD

**Issue by EduardsE** [spotify/spotify-web-api-ts-sdk#69]
Both are numbers and required. Is it meant to be the same value?
```
export interface AccessToken {
    access_token: string;
    token_type: string;
    expires_in: number;
    refresh_token: string;
    expires: number;
}
```

**Comment by kylelamkh** [comment]
<img width="129" alt="image" src="https://github.com/spotify/spotify-web-api-ts-sdk/assets/46770292/58ef1e02-a8c6-403a-b688-d0994f8116e2">

The value in `expires` is a timestamp while `exipres_in` is the time to live of the token

**Comment by davidwhitney** [comment]
Because the token is cached for use, we need to know when the token expires from its point of issuance.

I kinda agree that the typedef here is a bit sloppy and really it should be two types, but when folks are providing a token from another auth means, they're going to have to calculate an absolute expiry so the SDK is aware of requiring refreshes ahead of time.

Though I'm starting to wonder if it might not be better to just not try cope with that edge case, and always catch and refresh rather than refreshing up front.
